server/mock/create-large-amount-data.js, server/src/database/models/category.js, server/src/database/models/classification-pattern.js, server/src/database/models/mail.js, server/test/mail/database.bulk.spec.js, server/test/mail/database.spec.js, server/test/mail/service.spec.js
mail 테이블에서 더 이상 필요하지 않은 is_removed 삭제
category에서 default로 존재하는 category인지 아닌지 판단하기 위해 추가
1. mail 테이블의 is_removed 삭제
2. category 테이블에 is_default 추가
1. 휴지통도 카테고리로 구분하기로 하여 더 이상 필요하지 않음
2. 해당 카테고리가 default인지 아닌지 분리하기 위해 추가
is_removed가 있는 테스크 코드 전부 삭제
category 테이블의 category_no 칼럼이 생성되지 않도록 수정
=> fix: remove is_removed, add is_default

server/src/libraries/validation/user.js, server/test/mail/database.bulk.spec.js, server/test/mail/database.spec.js, server/test/mail/service.spec.js, server/test/mail_template/database.spec.js, server/test/user/api.spec.js, server/test/user/database.spec.js, server/test/user/service.spec.js
1. sequelize의 build를 통한 validation전 이름의 좌우 공백제거
2. 테스트 코드 테이블 초기화시 외래키 제약조건을 제거
1. 사용자가 실수로 띄어쓰기를 넣어 요청을 할 수도 있을 것 같아서 trim을 사용하여 좌우 공백 제거
2. 이름에 공백문자만 넣어서 건네줄 경우 에러로 간주해야 함
3. 데이터베이스에 남아있는 테이블의 row들이 서로 외래키로 참조하고 잇는 경우가 있어 삭제되지 않아 문제가 발생하는 경우가 있어서 초기화시 외래키 제약조건 제거
1. validation/user.js의 join 함수에서 body.name이 존재할 경우 body.name을 trim을 시켜주도록 함
=> sequelize의 build를 통한 validation을 하기 전 이름의 좌우 공백제거, 테스트코드 변경

server/src/libraries/validation/mail.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js, server/test/libraries/mail/quey.spec.js, server/test/mail/api.spec.js, server/test/mail/service.spec.js
1. mail service계층에 getMailsByOptions함수에서 category가 0이면 db query filter에서 category제거함으로써 전체 메일함 쿼리로 만듬
2. getQueryByOptions 함수를 통해 category 값에 따른 query를 얻을 수 있도록 함수 분리
1. 유연한 확장을 위해 분리
2. 재활용 가능하도록함
=> [server] 페이징처리시 category가 0일때 category를 필터에서 제거

server/src/database/models/user.js, server/src/libraries/exception/error-code.js, server/src/libraries/mail-util.js, server/src/libraries/replace.js, server/src/libraries/validation/user.js, server/src/v1/auth/service.js, server/src/v1/mail/service.js, server/src/v1/users/controller.js, server/src/v1/users/index.js, server/src/v1/users/service.js, server/test/user/api.spec.js, server/test/user/service.spec.js
1. 아이디 찾기 API를 구현
2. 이메일을 찾을 수 없을 경우의 상태코드를 만듬
3. 아이디 찾기 API의 type에 부적절한 값이 들어올 경우 에러 발생
1. 사용자가 아이디를 찾을때 잘못된 쿼리나 이메일로 API 요청할 경우 적절한 에러 정보를 보여주기 위해서 
1. 적절한 type 정보가 body에 있는지 확인하는 checkQueryForSearch 함수 추가
2. 적절한 email 정보가 body에 있는지 확인하는 checkBodyForIdSearch 함수 추가
3. 데이터베이스로 부터 email을 가지고 있는 유저를 찾아서 해당 유저의 email로 메일을 보내주는 sendUserIdToEmail 함수 추가
=> [BE] 아이디 찾기 API 구현

server/src/database/models/user.js, server/src/libraries/crypto.js, server/src/middlewares/passport.js, server/src/v1/auth/service.js, server/src/v1/users/service.js, server/test/crypto.spec.js
1. 회원가입시 암호화 알고리즘 변경
2. 회원가입시 암호화에 사용하는 Salt값을 함께 DB에 저장
1. Dovecot SASL 인증을 위한 암호화 방식 통일
1. 메일 서버 DB의 user 추가시 비밀번호를 다음과 같은 형식으로 지정
`
ENCRYPT('password', CONCAT('$6$', SUBSTRING(SHA(RAND()), -16)))
`
2. query 결과값이 buffer라서 string형으로 바꿔주기 위하여 toString() 사용
3. MySQL Encryption and Compression Functions
https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html
=> [BE] 회원가입 암호화 알고리즘 변경

server/package-lock.json, server/package.json, server/src/database/models/user.js, server/src/libraries/exception/error-code.js, server/src/libraries/generator.js, server/src/libraries/mail-util.js, server/src/libraries/validation/user.js, server/src/v1/users/controller.js, server/src/v1/users/service.js, server/test/generator.spec.js, server/test/user/api.spec.js, server/test/user/service.spec.js, server/test/validator.spec.js
1. 비밀번호 찾기 API 구현 (임시비밀번호를 생성하여 메일로 보내줌)
2. generator 모듈의 무작위 문자열을 생성하는 createRandStr 함수 구현
3. 임시비밀번호 생성시 createRandStr 함수를 사용
1. 보통 비밀번호를 찾을 때 임시비밀번호를 메일로 보내줌
2. createSalt 같은 경우 DB에 쿼리를 보내는 방식으로 무작위 문자열을 생성하여 비효율적이라서 새로운 무작위 문자열 생성 함수 구현
1. 임시 비밀번호를 메일로 보내기 위해서 `.env` 파일에 메일 계정을 설정해야함. 
회원가입 페이지를 통해 회원정보를 DB에 등록하고 설정해도 됨
```bash
MAIL_AUTH_USER=
MAIL_AUTH_PASS=
```
=> [BE] 비밀번호 찾기 API 구현

web/components/Aside/index.js, web/components/Header/index.js, web/components/MailTemplate/index.js, web/components/ReadMail/PageMoveButtonArea/index.js, web/components/ReadMail/index.js, web/contexts/reducer.js, web/pages/index.js
1. 기존에 context의 state에 있던 selected를 제거하고 view를 추가하여 view의 상태관리를 통해 메일리스트, 메일읽기, 메일쓰기 화면 전환이 가능하도록 변경
1. selected는 메일리스트 <-> 메일읽기 화면 전환만 고려하였기 때문에 메일 쓰기에서 메일 보관함 클릭 시 화면 회전이 되지않았음. 이를 수정하기 위해 selected 삭제하고 view를 추가
돌아가는거에 집중하여 수정했으므로 부족한 부분이 있을 수 있음
=> 전역 context의 state에 view 추가

web/components/Header/index.js, web/components/ReadMail/PageMoveButtonArea/styled.js, web/components/ReadMail/ToolGroup/index.js, web/components/ReadMail/ToolGroup/styled.js, web/components/ReadMail/index.js
1. 다른 카테고리에서 Header 클릭 시 전체메일함 이동 오류 수정
2. 메일읽기 상단 툴바 외형만 구현
1. 단순하게 setView -> handleCategoryClick으로 변경
2. 추후 업데이트 될 예정 일단 메일 삭제 구현해야됨
header클릭이 category 클릭이 아니지만 전체메일함 카테고리 클릭과 같은 효과이므로 재활용
=> [FE] 다른 카테고리에서 전체메일함 이동 오류 수정 / 메일읽기 상단 툴바 외형만 구현

web/components/Forms/FindIdForm/index.js, web/components/Forms/FindPwForm/index.js, web/components/Forms/LoginForm/index.js, web/components/Forms/PwChangeForm/index.js, web/components/Forms/PwChangeForm/styled.js, web/components/Forms/RegisterForm/index.js, web/components/MessageHeader/index.js, web/components/MessageHeader/styled.js, web/components/Profile/index.js, web/contexts/reducer.js, web/pages/login.js, web/utils/success-message.js
1. 회원가입 후 로그인 페이지에서 메시지 표시
2. 사용자에게 보여줄 메시지를 ContextAPI를 사용하여 관리하도록 함
3. Router event (routeChangeStart)를 사용하여 페이지 이동시 메시지 상태를 초기화 하도록 함 
4. 다른 페이지에서 로그인 페이지로 이동시에는 메시지 상태를 초기화 하지 않도록 함
1. Router를 통해 query를 push할 경우 URL에 query가 표시되어서 더러워짐
2. routeChangeStart에서 메시지를 다시 초기화 하기 때문에 메시지 설정 후 "로그인 페이지"로 이동할 때에는 제외 하도록 함 
```javascript
const handleRouteChange = url => {
if (url !== '/login') {
dispatch(setMessage(''));
}
};
Router.events.on('routeChangeStart', handleRouteChange);
```
1. next/router의 Router 객체는 여러가지 이벤트를 다음과 같이 여러가지 이벤트를 등록할 수 있음
`routeChangeStart(url)`: Fires when a route starts to change
`routeChangeComplete(url)`: Fires when a route changed completely
`routeChangeError(err, url)`: Fires when there's an error when changing routes, or a route load is cancelled …
=> [FE] 회원가입 후 메시지 표시

web/components/WriteMail/DropZone/index.js, web/utils/available-extension.js, web/utils/request.js
1.이미지 업로드시 확장자와 사이즈 검사
1. 허용가능한 범위의 파일만 받음
2. 확장자를 아무거나 받으면 보안에 위협적
=> FE 파일확장자 & 사이즈 검사 로직추가

web/components/Aside/index.js, web/components/MailArea/MailTemplate/index.js, web/components/MailArea/Tools/index.js, web/components/MailArea/index.js, web/components/ReadMail/PageMoveButtonArea/index.js, web/components/ReadMail/ToolGroup/index.js, web/components/ReadMail/index.js, web/utils/error-handler.js
1. 로그인 시 해당 유저가 가지고 있는 카테고리 목록들을 받아와 aside에서 출력한다.
1. 유저 별로 같은 default 카테고리이어도 category.no가 다르기 때문에 유저별 카테고리 목록을 로드할 필요가 있었다. 이를 위해 utils의 useFetch를 이용하였고 useCallback을 통해 계속해서 데이터를 요청하는 것을 방지
차후에는 카테고리 목록을 context에 넣어서 관리를 할 생각이다. 카테고리를 추가하거나 삭제하면 aside가 재렌더링 되어야 되기 때문에...
=> [FE] 로그인 시 카테고리 목록 로드

infra/maildb/node-runner.sh, infra/maildb/src/app.js, infra/maildb/src/env.js, infra/maildb/src/format.js, infra/maildb/src/ncloud.js
1. 메일 수신 시 ncloud object storage 저장하고 반환한 url값을 attahcment DB에 저장
2. env.js 추가
1. 수신한 메일의 첨부파일도 우리 서버에서 관리해야하고 DB에는 buffer가 아닌 url을 저장하기 때문
2. 기존에는 node-runner에서 설정값들을 넘겨받았지만 ncloud.js 파일도 추가되면서 이 방법이 불편하다고 느낌. 그래서 env.js 파일을 새로 만듦. 보안을 위해 value들은 "" 처리하였음.
.txt .jpg 는 수신할 때 postfix hook이 발생하는 것을 확인하였지만, png는 hook이 발생하지 않음. 추후 whitelist에 추가만하면 해결될 듯 하다.
=> [Infra] 메일 수신 시 첨부파일 DB 저장

server/src/v1/admin/mail/service.js
1. 메일 예약 전송시 attachment를 object storage로 부터 파일을 받아와서 첨부하여 함께 전송
1. 예약 메일 등록시 attachment 같은 경우는 object storage에 저장하도록 함. 따라서 예약 전송시 object storage의 attachment를 받아와 전송하도록 함
[Stream으로 부터 데이터를 받아오는 방법](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#createReadStream-property)
=> [BE] 예약 메일 전송 API - 첨부 파일 전송

web/components/Forms/RegisterForm/index.js
1. 회원가입 페이지에서 폼 입력시 즉각적으로 에러 메시지 표시
1. 가입하기 버튼을 눌렀을 때 에러 메시지를 표시하는 것 보다 입력을 할 때 문제가 있을 경우 에러 메시지를 표시하는 것이 좋다고 판단
1. 비밀번호 재입력 필드의 경우에만 가입하기 버튼을 눌렀을 때 제대로 입력되었는지 확인하여 에러 메시지 표시
=> [FE] 회원가입 페이지에서 폼 입력시 즉각적으로 에러 메시지 표시

server/src/database/models/user.js, server/test/user/database.spec.js
1. 회원가입시 이름에 특수문자가 포함되어 있어도 정규식으로 걸러내지 못 하는 문제 해결
1. 정규식으로 이름 형식을 확인하는데 길이를 넣지 않을 경우 정규식이 제대로 특수문자를 걸러내지 않아서 길이를 넣음
1. validate의 "len" 필드를 "is" 필드를 위로 올릴 경우 "len" 부터 조건에 맞는지 확인 후 "is"의 정규식이 조건에 맞는지 확인함. 순서를 보장하는 것 같음.
=> [BE] 회원가입시 이름 정규식 특수문자 확인 못하는 문제 해결

web/components/MailArea/index.js
1. MailArea 컴포넌트 내부에서 코드를 외부로 분리
1. MailArea 내부 로직이 너무 많아서 분리
전에는 안되던데 이번엔 왜 되누
=> [FE] handleAction 객체 함수 컴포넌트 외부로 분리

server/src/v1/mail/service.js, server/test/libraries/mail/attachment.spec.js, server/test/mail/api.spec.js, server/test/mail/service.spec.js
1. 메일리스트 시간정렬
1. no에서 createdAt으로 변경
예약기능이 들어오면서 정렬대상을 createdAt으로 수정
=> fix(be/mail): 메일리스트 시간정렬 #313

server/src/database/models/mail.js, server/src/libraries/validation/mail.js, server/src/v1/mail/service.js
1. update 될 때마다 prev_category_no를 변경 전 category_no로 저장한다.
1. 메일 복원을 구현하려면 삭제 전 이전 카테고리를 알고 있어야한다. 이전 카테고리 번호를 저장할 prev_category_no라는 column을 mail table에 추가
카테고리 변경이 아니어도 해당 연산은 수행하지만 코드 1줄 더 실행되는거 무슨 차이가 있겠습니까
=> [BE] 휴지통 복원

web/components/Forms/FindIdForm/index.js, web/components/Forms/FindPwForm/index.js, web/components/Forms/PwChangeForm/index.js, web/components/Forms/RegisterForm/index.js, web/utils/error-message.js, web/utils/error-parser.js, web/utils/success-message.js
1. 프론트엔드 버그 수정
- 아이디, 비밀번호 찾기 에러 #311
- request 모듈을 사용
- 회원가입시 중복 이메일 에러 메시지 #318
- 서버에서 아이디, 이메일 중복일 경우 에러 메시지를 적절히 반환
- 회원가입시 중복 아이디 에러 메시지 표시 위치 #321
- 메시지 내용에 따라 위치를 정하도록 함
- 비밀번호 포커스 아웃 문제 #322
- password 처리 핸들러를 따로 만듬
1. 회원가입시 중복 이메일, 아이디 에러 메시지 처리 같은 경우 request 모듈에서 status, message를 꺼내어 반환하기 때문에 message 내용에 따라 에러 메시지를 표시할 위치를 정하도록 함
라우팅 문제, 로그아웃 문제 해결 필요
=> 회원가입,로그인 버그 수정 #311 #318 #321 #322

server/src/libraries/exception/error-code.js, server/src/v1/users/service.js, server/test/user/service.spec.js
1. 이메일 중복 가입 처리를 위한 에러 처리 코드 추가. 가입시 아이디만 중복되거나, 이메일만 중복되거나 아이디와 이메일이 중복되는 경우가 발생할 수 있어서 경우에 따라 에러 메시지 반환
1. 기존 코드(테스트, 클라이언트 에러 처리)를 최대한 바꾸지 않고 작성을 하기 위해 해당 방법을 선택함.
=> [BE] 이메일 중복 가입 처리를 위한 에러 처리

server/src/libraries/mail-util.js
1. Hotfix - 메일 전송시 메세지 아이디 뒤에 도메인 추가
1. 다른 메일 서비스에서 메세지 아이디 뒤에 도메인을 넣어주기 때문
- 표준으로 보임
=> [BE] Hotfix - 메일 전송시 메세지 아이디 뒤에 도메인 추가

server/src/database/models/user.js, server/src/v1/users/service.js
1. 가입시 넘겨준 id와 sub_email에 정보를 가진 회원이 각각 다를 경우 (id로 sub_email' 정보로 가입한 회원, id', sub_email 정보로 가입한 회원)를 따로 처리를 할 수 있도록 함
1. id, sub_email 정보로 가입한 회원이 2명이 될 수 있음. 반면 findOrCreateById 함수는 한 명의 회원만 반환하여 제대로 된 에러처리가 안되는 경우가 발생할 수 있음
=> [BE] id로 가입한 회원과 sub_email로 가입한 회원이 서로 다를 경우 처리

web/components/ReadMail/PageMoveButtonArea/index.js, web/components/ReadMail/PageMoveButtonArea/styled.js
1. 1001에서 이전 페이지를 누르면 909로 가는 버그가 있었음. index를 mails의 길이만큼 설정하는 부분을 기존의 mails가 아닌 새롭게 load한 mails의 길이로 설정하도록 변경
1. 현재 index가 새롭게 저장된 mails의 마지막 인덱스를 가리키기 위해
갓재호
=> fix(fe/read-mail): 페이지 변경 시 이전 메일 보기 오류 수정

server/src/libraries/validation/attachment.js, server/test/date-parser.spec.js, server/test/libraries/mail/attachment.spec.js
1. 메일전송시 첨부파일를 미디어타입 검사에서 확장자 검사로 변경
1. 네이버에서 제공하는 블랙리스트를 발견함
=> fix(be/attachment): 첨부파일 확장자 검사 블랙리스트로 변경 #317

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/MailTemplate/styled.js, web/components/MailArea/Tools/index.js, web/components/MailArea/index.js, web/components/ReadMail/Tools/index.js, web/components/ReadMail/index.js, web/components/ReadMail/styled.js, web/utils/request.js
1. 체크가 된 mail들은 selected값이 true이므로 이것을 이용하여 category_no를 업데이트하여 휴지통으로 이동될 수 있도록 구현
2. 메일리스트에서 체크박스 또는 버튼으로 영구삭제 기능 구현
3. 기존에 휴지통의 복구 버튼을 영구삭제 버튼으로 교체하고 휴지통에서 메일읽는 화면에 복구와 영구삭제 기능을 추가 
1. MailArea의 자식으로 Tools 컴포넌트가 있는데 체크박스를 통해 다수의 메일을 삭제하기 위해서는 이 둘의 컴포넌트가 양방향으로 통신할 수 있어야한다. 따라서 context에 메일리스트를 저장해두고 selected 값을 바꿔주는 것을 통해 해당 기능을 구현하였습니다.
2. 1번의 방법과 동일
3. 다수결로 인해 해당 위치에 복구버튼을 영구삭제 버튼으로 교체
=> [FE] 체크박스를 통해 메일삭제 #344 / 메일 영구 삭제 #238

web/components/MailArea/Tools/index.js, web/components/MailArea/index.js, web/components/ReadMail/Tools/index.js, web/components/ReadMail/index.js, web/utils/mail-request.js
1. 기존에는 다수 메일 업데이트/삭제 로직과 단일 메일 업데이트/삭제 로직이 공존하고 있었다. 이를 다수 메일 업데이트/삭제 로직으로만 처리할 수 있도록 변경하였고 각 컴포넌트에 선언된 updateMail()과 removeMail()을 제거하고 utils/mail-request를 만들어서 공통으로 사용
1. 다수 메일 처리는 배열을 서버로 넘겨주는데 배열에 하나의 값만 넣어서 보내는 것이 곧 단일 메일 처리에 해당한다. 따라서 나누지 말고 다수 메일처리로 모두 처리할 수 있도록 변경.
=> [FE/Refactor] 단일 메일 업데이트/삭제 로직 제거

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/MailTemplate/styled.js, web/components/MailArea/Tools/index.js, web/components/MailArea/index.js, web/components/ReadMail/Tools/index.js, web/components/WriteMail/InputSubject/index.js, web/components/WriteMail/index.js
1. 답장 버튼 클릭 시 한 개의 메일인지 from이 누구인지 확인한 후 WriteMail 컴포넌트에 해당 메일의 정보를 넘겨주고 제목과 받는 사람의 default값을 지정하도록 한다.
1. 답장은 한 사람, 한 사람 소중하게 생각해서 보내야 하며 하나의 메일만 클릭하였을 때 답장을 보낼 수 있다. (네이버와 동일) 그리고 자신한테 답장을 보내는건 이상한 짓이므로 배제하였음.
내용도 담으려고 했지만 내용을 보여주기 위해서는 WriteMail에서도 TUIViewer가 필요하며 불필요한 태그값을 담아서 보내게 되므로 제거
=> [FE] 메일리스트/메일읽기에서 답장 기능 구현

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/MailTemplate/styled.js, web/components/MailArea/Paging/index.js, web/components/WriteMail/InputReceiver/index.js, web/components/WriteMail/InputSubject/index.js
1. defaultRecevier을 정규식으로 확인하여 이메일 값만 추출할 수 있도록 extractAddres() 추가
1. 네이버에서 받은 메일의 경우 보낸 주소가 "배형진 <dkwk1254@naver.com>"이다. 따라서 이메일 주소값만 추출하는 로직이 필요하므로 추가
MailTemplate의 style component 변수명 변경
=> [FE] hofix: 답장 시 보낸 주소에서 이메일만 추출하는 함수 추가

web/components/Forms/LoginForm/index.js, web/components/Header/Search/Input/InputDate.js, web/components/LogoutButton/index.js, web/contexts/reducer.js, web/higher-order-component/with-authentication.js, web/hook/use-authentication.js, web/pages/_app.js, web/static/date.css, web/static/react-datepicker.css
1. 로그아웃 후 세션 초기화 및 Router를 사용하여 로그인 페이지로 이동
2. 로그인 페이지 접속시 useEffect를 통해 Router 이벤트 등록 후 이벤트 처리가 종료됬을 경우 이벤트 삭제하여 이벤트가 중복되어 등록되는 것을 방지
3. Header/Search/InputDate.js의 css 파일 로드를 제거하였으며 static 폴더아래 제거한 css 파일을 추가하여 _app.js에서 불러오도록 함
1. window.location.href를 사용하여 새로 페이지를 불러오는 것 보다 Router.push를 사용하여 클라이언트 사이드로 렌더링하여 빠르게 화면 전환을 하도록 함
2. `next-css`의 버그로 _app 폴더에서 css를 불러오지 않으면 page가 로드되지 않을 수 있다고 함 
[Links to some pages are hanging on navigation with `next-css` plugin](https://github.com/zeit/next.js/issues/7886)
[_app.js에서 CSS 파일 불러오는 방법](https://github.com/zeit/next.js/issues/299)
=> [FE] 라우팅 문제 해결 및 InputDate 컴포넌트 css 파일 로딩 방식 변경

server/src/libraries/mail-util.js
1. 메일 전송을 위한 transporter를 미리 생성
1. 예약 메일 수십개 발송시 too many connection 에러가 발생하여 효율성을 개선하기 위해 transporter 미리 생성
[SMTP server too many connection 에러 해결](https://github.com/nodemailer/nodemailer/issues/699)
2. 메일 전송시 보낸메일함에 메일을 저장하기 위해 imap 연결을 따로 하기 때문에 SMTPS 연결시 사용자 계정으로 접속할 필요없이 루트 계정으로 접속하여 사용해도 문제 없음
- 또한 dovecot imap에 여러명의 유저가 접속할 경우 발생하는 `Maximum number of connections from user+IP exceeded` 에러를 수정하기 위해 `/etc/dovecot/dovecot.conf` 파일에 max-connection수 설정
```
protocol imap {
mail_max_userip_connections = 1000
}
```
[Dovecot ignoring maximum number of IMAP connections](https://serverfault.com/questions/385187/dovecot-ignoring-maximum-number-of-imap-connections)
=> fix(be): 예약 메일 전송을 위한 transporter 미리 생성

web/components/MailArea/index.js, web/components/ReadMail/PageMoveButtonArea/index.js, web/components/ReadMail/Tools/index.js, web/components/ReadMail/index.js, web/contexts/reducer.js, web/utils/url/change-query.js
1. 전역 state.mail을 삭제하고 ReadMail에서 mail 변수를 새로 만들어서 상태관리하는 로직으로 변경
1. url을 통해 화면전환으로 변경 된 후 메일읽기에서 새로고침 시 state.mails 값이 null이 됨. 따라서 메일읽기에서 새로 메일리스트를 서버로부터 로드하여 ReadMail 내에 있는 mail의 상태를 변경하도록 수정
이 리팩토링을 보면 state.mails 역시 삭제 가능한 부분이 아니냐는 의문이 들 수 있다. 하지만, 이미 state.mails는 많은 컴포넌트에 영향을 미치고 있으며 성능적 이슈도 없기 때문에 리팩토링 우선순위를 미룸
=> [FE/리팩토링] 전역 state.mail 삭제

server/src/libraries/exception/error-code.js, server/src/middlewares/sync-with-imap.js, server/src/v1/auth/controller.js
1. 로그인할 때 IMAP과 DB 메일/메일함 동기화 실패시 에러처리 추가
1. 동기화하지 못하면 로그인하지 못하도록 함<br>버그를 유발할 수 있기 때문이었습니다
=> [BE] 로그인할 때 IMAP과 DB 메일/메일함 동기화 실패시 에러처리 추가

web/components/MailArea/index.js
1. rotuer.query.category 사용
1. 이전에 쓰던 state.category를 지웠으므로 rotuer.query.category를 사용
=> Hoxfix(fe/mail-area): headTitle에 undefined 뜨는 에러 수정

web/components/Aside/index.js, web/components/MailArea/MailTemplate/index.js, web/components/MailArea/Tools/index.js, web/components/MailArea/index.js, web/components/ReadMail/PageMoveButtonArea/index.js, web/components/ReadMail/Tools/index.js, web/components/ReadMail/index.js
1. 이전/다음 버튼 눌렀을 때도 MailArea에서 요청한 url의 형태를 그대로 사용
1. 이전/다음 메일을 읽을 때 순서를 검색, 정렬된 순서로 읽을 수 있기 위해
urlQuery 마음에 안들어서 다 지움.
urlQuery -> query (router destructing)
query -> queryString
=> perPageNum이 변경된 후 이전/다음 메일 보기 버그 수정 #439

server/src/v1/admin/mail/controller.js, server/src/v1/admin/mail/service.js, server/test/admin/mail/api.spec.js
1. 기존 promise.all을 제거하여 수행결과를 받아오지 않도록 하도록 함
1. 전송한 예약 메일을 반환하지 않도록 하여 응답 속도 개선
=> [BE] 전송한 예약 메일을 반환하지 않도록 하여 응답 속도 개선

server/src/database/models/mail.js, server/src/middlewares/sync-with-imap.js
1. imap과 sync맞추는 부분에서 get db mails 함수 for문 하나 줄임
2. 정환이의 resultVation 수정
1. `Op.or`와 `Op.in`이 있었는데, `Op.in`의 연산 결과가 더 빠르기에 선택함
=> [BE] imap과 sync맞추는 부분에서 get db mails 함수 for문 하나 줄임

server/src/database/models/category.js, server/src/database/models/mail.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js, server/test/mail/service.spec.js
1. mail의 message_id가 있는지 확인(hasMessageIdAllMails)하고 imap의 moveMail()을 통해 imap 연동
1. message-id가 없으면 imap 연동이 불가능하기 때문에 확인
더 이상 message-id가 없는 메일을 업데이트하면 에러 메시지 출력됨
=> [BE] 메일 카테고리 변경 시 imap 연동

server/src/v1/admin/mail/controller.js, server/src/v1/admin/mail/service.js
1. 예약 메일 전송 API의 return을 try문 안으로 넣음
2. promises => loadTasks
1. 코드 리뷰 반영
2. 변수명을 명확하게 수정
=> [BE] 예약 메일 전송 API의 return을 try문 안으로 넣음, 변수명 수정

server/src/v1/mail/service.js
1. moveMailInInfra()에서 예약된 메일들을 필터로 걸러내고 imap 연동이 진행되도록 변경
1. 예약메일의 경우 imap에 존재하지 않는 메일이므로
=> fix(be/mail/service): 예약메일 카테고리 변경 에러 수정 #478

web/components/MailArea/Tools/index.js, web/components/ReadMail/index.js
메일 수를 20->100으로 변경 시 총 페이지 수가 줄어들어 현재 페이지에서 메일이 존재하지 않는다는 문구가 떠서 메일수 변경 시 무조건 1페이지로 가도록 설정
=> fix(fe/mail-area): 메일수 변경 시 1 페이지로 설정

web/components/Aside/dialog-data.js
1.  메일함 추가하고 메일을 바로 이동시키면 undefined로 이동된 것으로 보임
1. 메일함 추가될 때 전역 state의 categories를 업데이트 해주는 라인추가로 수정
야레야레 재호가 놓치고 있었다구
=> fix(fe/dialog-data): 메일함 추가하고 바로 메일 이동시키면 undefined되어 있는 버그 수정 #483
