connect-foundation/2019-06

server/src/app.js
=> chore: add line

server/.editorconfig
=> feat: add editorconfig

server/src/app.js, server/src/bin/dbSync.js, server/src/database/makeData.js, server/src/database/models/mail.js, server/src/v1/mail/controller.js, server/src/v1/mail/index.js, server/src/v1/mail/service.js
=> feat: create mail api template

server/package.json, server/src/bin/dbSync.js, server/src/bin/www.js, server/src/database/create-dummy-data.js, server/src/database/models/user.js, server/test/index.spec.js
npm run dev는 db초기화 하지않고
npm run dev:force는 db초기화 모드
=> chore: write db init script in pakackge.json

web/components/Send_Mail/Receiver_List/index.js, web/components/Send_Mail/Receiver_List/styled.js, web/components/Send_Mail/index.js, web/pages/mail/send.js, web/utils/validator.js
이메일 comma, space, enter로 입력 데이터로 이메일 태깅
validator를 통과한 이메일이라면 하얀색, 통과하지 못했다면 빨간색으로 태깅
=> feat: email tagging

server/src/database/models/address.js, server/src/database/models/category.js, server/src/database/models/classification-pattern-type.js, server/src/database/models/classification-pattern.js, server/src/database/models/mail.js, server/src/database/models/user.js
=> feat: add models #57

web/components/index/Header/index.js, web/components/index/Header/styled.js, web/components/index/MailArea/index.js, web/components/index/MailArea/styled.js, web/components/index/MailTemplate/index.js, web/components/index/MailTemplate/styled.js, web/components/index/Tools/index.js, web/components/index/Tools/styled.js, web/package-lock.json, web/package.json, web/pages/index.js
=> feat: implement components of MailArea in index page

server/src/database/models/address.js, server/src/database/models/attachment.js, server/src/database/models/category.js, server/src/database/models/classification-pattern-type.js, server/src/database/models/classification-pattern.js, server/src/database/models/domain.js, server/src/database/models/mail-template.js, server/src/database/models/mail.js, server/src/database/models/user.js
=> chore: add utf8 set in models

server/src/database/models/user.js, server/src/libraries/error-code.js, server/src/libraries/validator.js, server/src/middlewares/validate-login.js, server/src/v1/auth/service.js, server/test/auth/integration.spec.js, server/test/validator.spec.js
로그인시 에러메시지를 수정하여 아이디, 비밀번호 중 어느 정보가 틀렸는지 모르도록 함
=> 로그인시 에러메시지 응답 수정

web/components/Aside/index.js, web/components/Aside/styled.js, web/components/GlobalStyle/index.js, web/components/WriteMail/DropZone/index.js, web/components/WriteMail/DropZone/styled.js, web/components/WriteMail/index.js, web/components/WriteMail/styled.js, web/pages/index.js
1. FE 레이아웃 setView 작업
1. 떠오른 생각이 setView를 props로 넘겨주는 방법이 생각이 났습니다
=> [FE] layout

web/contexts/index.js, web/contexts/reducer.js, web/pages/_app.js, web/pages/index.js
1. 전역 컨텍스트를 생성
1. 메일에서 사용할 상태를 공유하기위해
=> Fe/develop: 전역 컨텍스트 생성

web/components/Aside/index.js, web/components/Footer/styled.js, web/components/Loading/index.js, web/components/Loading/styled.js, web/components/MailArea/index.js, web/components/MailTemplate/index.js, web/components/Paging/PageNumber/index.js, web/components/Paging/index.js, web/contexts/index.js, web/contexts/reducer.js, web/pages/index.js
1. 페이징과 카테고리 동작하도록함
1. 일단 생각나는 방법이 이것이 유일했음.
2. 내일 데모를 위한 최선의 방법이었음
리액트를 공부해서 추후 최적화를 시도할것임.
=> fe 페이징처리 & 카테고리처리 #72 #143

server/src/app.js, server/src/database/models/mail.js, server/src/libraries/validation/mail.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js, server/test/mail/service.spec.js
메일필터객체 안에 넣어야 했는데,
외부에 넣어서 작동하지 않았음
1.메일리스트이 필터 미작동 
1.고치기 위한 유일한방법..
=> fix(be/mail): 카테고리 필터가 미작동했던점 #140

web/components/FindIdForm/index.js, web/components/FindIdForm/styled.js, web/components/LoginForm/index.js, web/components/RegisterForm/index.js, web/components/SmallHeader/index.js, web/components/SmallHeader/styled.js, web/pages/help/id.js
1. 아이디 찾기 화면을 구현하여 사용자는 가입에 사용한 이메일을 입력시 해당 이메일로 아이디 정보를 받을 수 있음
1. 사용자가 아이디를 찾을 수 있도록 함
1. 아이디 찾기 화면 구현 (FindIdForm/index.js)
=> [FE] 아이디 찾기 화면 구현

server/src/bin/www.js, server/src/libraries/paging.js
=> 페이징 함수 에로우 펑션으로 수정

web/components/Aside/index.js, web/components/Header/index.js, web/components/MailArea/Paging/index.js, web/components/MailArea/index.js, web/components/MailTemplate/index.js, web/components/ReadMail/PageMoveButtonArea/index.js, web/components/ReadMail/index.js, web/contexts/index.js, web/contexts/reducer.js, web/pages/index.js, web/utils/query.js, web/utils/request.js, web/utils/use-fetch.js
useEffect의 관심사를 URL에 집중하도록함으로써 의존성을 최소화시킴
1. useFetch와 mail-list 를 가져오는 방식 바꿈
1. useEffect의 관심사를 최소화 시키고, 유연하게 사용할 수 있도록 할 수 있어서
=> refactor: mail-fetch방식 변경

server/src/v1/mail/controller.js
1. mail list response 
1. {mail}에서 mail로 변경.
client 에서 data.mails.mails 처럼 이상해짐
=> fix: mail list 반환형식 변경

web/utils/http-response.js, web/utils/request.js, web/utils/use-fetch.js
try catch는 한곳에서 한다.
1. util/request
1. 어떤 메소드를 사용하든 error parser를 한번만 하도록 구조변경
=> fix: request 유틸 구조변경

web/components/Forms/RegisterForm/index.js
1. RegisterForm의 onBlur 함수를 onChange 함수로 변경
1. onChange를 통해 상태를 바로 업데이트 하도록 함
=> fix(fe): onBlur => onChange

web/components/Forms/RegisterForm/index.js, web/components/MailArea/index.js, web/utils/error-parser.js, web/utils/use-fetch.js
1. 인덱스 페이지 에러처리
1. 그저 갓.. 님들도 감동할꺼임
=> 인덱스 페이지 에러처리

infra/maildb/src/app.js, infra/maildb/src/format.js
1. 받은 메일에 파일이 있는 경우 Attachment 테이블에 저장
1. attahcment를 저장하기 위해서는 mail_template_id가 필요하므로 mail_template에 데이터를 저장 후 실행
현재는 첨부 파일이 간단한 .txt 파일만 수신이 가능하다. 아직 이미지 파일 수신시에는 postfix hook이 발동하지 않는다. 차후에 수정해야할 것 같다.
=> [Infra] 파일첨부한 메일 수신 시 Attachment 테이블에 저장 Issue #191

server/src/libraries/validation/mail.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js, server/src/v1/users/service.js, server/test/libraries/mail/quey.spec.js, server/test/mail/service.spec.js
1. 메일리스트 정렬 [보낸사람, 제목기준]
1. 기존 코드를 사용하여 최소시간을 소요하여 최고 코드를 작성
=> BE 보낸사람, 제목기준 메일리스트정렬 #164 #165 #167 #168

server/src/libraries/date-parser.js, server/src/libraries/exception/error-code.js, server/src/libraries/save-to-infra.js, server/src/libraries/validation/date.js, server/src/libraries/validator.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js, server/test/date-parser.spec.js, server/test/mail/api.spec.js, server/test/validator.spec.js
1. 메일 보내기 예약 API 구현
2. 메일 전송 API에 body값에 reservationTime을 함께 전송할 경우 분기하여 처리
3. saveMail을 이용하여 예약 메일 저장
1. 기존의 메일 테이블을 사용할 수 있도록 함
=> [BE] 메일 보내기 예약 API 구현

infra/postfix/advanced-content-filter.py
1. advanced content filter python 코드 추가
1. Simple Content Filter를 적용하였을 때는 Daitnu끼리 보낼 때 훅스가 발동이 안되어서 공식문서에서 제안한 방법인 Advanced Content Filter를 적용하여 Daitnu끼리 보낼 때도 훅스가 발동되도록 하기 위함
[해당 깃허브](https://github.com/MiroslavHoudek/postfix-filter-loop)를 참고하였음
=> feat(infra): advanced content filter python 코드 추가

web/components/Aside/index.js, web/components/MailArea/Tools/index.js, web/components/MailArea/Tools/styled.js, web/contexts/reducer.js
1. 임시의 배열에 카테고리들을 분류하고 나서 임시 배열을 실제 출력하는 배열에 덮어씌우는 형식으로 오류 수정
1. 전역으로 선언된 defaultCategories와 userDefinedCategories에 push하여 다른 사용자로 로그인하면 계속 쌓이기 때문에 덮어씌우는 것으로 대체
더 좋은 방법이 있을 것 같습니다. 알려주시면 감사하겠습니다.
=> [hotfix] 로그아웃하고 다시 로그인하면 카테고리가 계속 누적되는 버그수정

server/src/v1/mail/box/controller.js, server/src/v1/mail/box/index.js
1. rest 방식을 따르도록 수정
1. REST API에서 delete와 patch 메소드의 사용 가이드르 따르도록 노력하기 위해
=> fix(be): mailbox api에서 받아오던 변수들 rest를 따르도록 수정

infra/maildb/src/app.js
1. mail.headers에서 정규식을 통해 실제 수신되는 메일 주소 추출하여 추출된 메일 주소가 있다면 해당 주소만 owner로 지정하여 DB에 저장
1. naver와 daum의 경우 headers에 실제 받는 사람의 메일 주소가 포함되어 있으며 수신자의 수만큼 hook이 발생하므로 실제 받는 사람의 메일 주소만 owner로써 DB에 저장하면 중복 수신을 방지할 수 있다.
[참고](https://hackmd.io/3xps1tB7Rj-Wi38sRQ-SOA?both)
=> fix(infra/maildb): 타 도메인 다중전송 메일 수신 시 중복 수신 버그 수정 #222

server/src/libraries/validation/attachment.js, server/src/v1/mail/controller.js, server/test/libraries/mail/attachment.spec.js
1. 첨부파일 토탈 사이즈 및 미디어 타입 체크
1. BLACK_LIST보다 WHITE_LIST가 안전함.
다음주엔 Object storage랑 연동하겠음
=> BE 첨부파일 토탈 사이즈 및 미디어 타입 체크

server/src/libraries/save-to-infra.js, server/src/libraries/validation/mailbox.js, server/src/v1/mail/box/service.js, server/test/mail_box/api.spec.js
1. 메일함 이름 유효성체크 추가 및 테스트코드 수정
1. 숫자도 넣고 싶은 유저가 있기 때문
=> [BE] 메일함 이름 유효성체크 추가 및 테스트코드 수정

web/components/Aside/dialog-data.js, web/components/Aside/index.js, web/components/Aside/styled.js, web/components/MailArea/MailTemplate/index.js, web/components/MailArea/Tools/index.js, web/components/MailArea/index.js, web/contexts/reducer.js
1. 최상단의 체크박스를 클릭하면 모든 메일이 선택되고 아니라면 풀리는 작업
2. Aside 선택시 색이 변하며 버튼이 아닌 텍스트로 변경
3. 커스텀 메일함도 또한 메일을 불러오도록 구현
1. 선택한 메일을 원하는 메일함으로 옮겨야함 그러기 위해선 각 메일마다 selected라는 속성을 주는 방법과 배열에 넣는 방법이 있었습니다. 둘 중 selected라는 속성을 주는 방법을 선택하였는데 이유는 배열에 넣게된다면 메일 선택을 해제할 때 마다 매번 find해서 제거해야 하는 점과 binary search를 한다 하여도 체크되는 메일들은 순서를 보장받지 못하기 때문입니다.
2. UX적인 문제였습니다. 기존에는 어떤 메일을 선택했는지 몰랐었기 때문에 추가하였습니다.
3. 커스텀 메일함도 메일을 볼 수 있어야 합니다
=> [FE] 메일함 체크박스 / Aside

web/components/MailArea/index.js, web/config/axios-config.js, web/pages/_app.js
1. config 파일제거
1. config파일이 request의 default url을 덮어씀
=> fix: 불필요한 axios config제거

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/MailTemplate/styled.js, web/components/ReadMail/index.js, web/components/ReadMail/styled.js
1. 보낸메일함 예약 메일 표시
1. 보낸메일함에서 보낸 메일과 함께 예약 메일을 한번에 볼 수 있어서 편리함
=> [FE] 예약 메일 표시

server/src/app.js, server/src/database/models/attachment.js, server/src/database/models/mail-template.js, server/src/libraries/validation/mail-template.js, server/src/v1/mail/index.js, server/src/v1/mail/template/controller.js, server/src/v1/mail/template/index.js, server/src/v1/mail/template/service.js, server/test/attachment/database.spec.js, server/test/mail_template/api.spec.js, server/test/mail_template/database.spec.js, server/test/mail_template/service.spec.js
1. 첨부파일 가져오기 구현
1. 메일을 읽었을때 첨부파일만 가져오도록 구현
=> feat(be/mail): 첨부파일만 갖고오기 구현

server/src/app.js, server/src/bin/www.js, server/test/auth/api.spec.js, server/test/mail/api.spec.js, server/test/mail_box/api.spec.js, server/test/mail_template/api.spec.js, server/test/user/api.spec.js
도메인 호스트가  v1이기떄문에 불필요한 경로
1. v1경로 제거
1. 호스트가 v1
=> fix: route경로 v1제거

web/utils/request.js
1.BE 경로수정
1. 호스트가 V1 이기때문에 경로에 v1을 사용할 필요가 없음
=> fix: be 경로수정

web/components/ReadMail/FileList/File/index.js, web/components/ReadMail/FileList/File/styled.js, web/components/ReadMail/FileList/index.js, web/components/ReadMail/FileList/styled.js, web/package-lock.json, web/package.json
1. 첨부파일 다운로드
1. 보안을 위해 서버를 경유하여 다운로드
=> feat(fe/attachment): 첨부파일 다운로드 #255

web/components/WriteMail/ReservationDateText/index.js, web/components/WriteMail/ReservationDateText/styled.js, web/components/WriteMail/SubmitButton/index.js, web/components/WriteMail/SubmitButton/styled.js, web/components/WriteMail/index.js, web/components/WriteMail/styled.js
1. 메일 보내기를 할때 메시지 표시 위치를 옮김
1. 기존 메시지 보내기 화면을 원상복구
=> fix(fe): 메일 보내기시 메시지 표시 위치

server/src/database/models/attachment.js, server/src/libraries/storage/ncloud.js, server/src/v1/mail/attachment/controller.js, server/src/v1/mail/attachment/index.js, server/src/v1/mail/attachment/service.js, server/src/v1/mail/index.js, server/test/attachment/api.spec.js, server/test/attachment/database.spec.js, server/test/attachment/service.spec.js
=> feat(be/attachment): 첨부파일 다운로드 #233

server/mock/create-large-amount-data.js, server/src/app.js, server/src/database/models/attachment.js, server/src/libraries/mail-util.js, server/src/libraries/storage/ncloud.js, server/src/v1/mail/attachment/controller.js, server/src/v1/mail/attachment/index.js, server/src/v1/mail/attachment/service.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js, server/src/v1/mail/template/service.js, server/test/attachment/database.spec.js
1. 첨부파일에 size 컬럼 추가
1. 사용자에게 첨부파일의 크기를 보여주기 위함
=> fix(be/attachemnt): 첨부파일 모델에 size 컬럼 추가

web/components/ReadMail/FileList/index.js, web/package-lock.json, web/package.json
1. 메일 읽었을때, 첨부파일 사이즈 표기
1. 첨부파일의 용량을 알려주기위해
=> feat(fe/readmail): 첨부파일 사이즈 표기

server/src/bin/www.js, server/src/libraries/save-to-infra.js, server/src/v1/mail/controller.js, server/src/v1/mail/service.js
1. 내게 쓰기
메일함 이름에 따라 메일을 넣는 함수 구현
1. 보낸메일함에 넣을 때도 있고 내게 보낸 메일함에 넣을 때도 있기 때문
=> [BE/Infra] 내게 쓰기

server/src/database/models/mail-template.js, server/src/libraries/mail-util.js, server/src/v1/mail/controller.js, server/test/libraries/mail/util.spec.js
1. 메일 전송시 text, html 둘다전송
1. 표준을 위하여
=> feat(be/mail): 메일 전송시 text, html 둘다전송

server/src/config/cors-options.js, server/src/libraries/exception/error-code.js, server/src/middlewares/auth.js
1. CORS에 ORIGIN WHITE_LIST와 METHOD 추가
1. 보안을 위해 연습해봄
=> feat(be/cors): 허용된 메서드 제한

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/MailTemplate/styled.js, web/components/MailArea/index.js
1. 전체 메일 클릭시 어느 메일함의 메일인지 표시
1. 전체 메일을 클릭했다면 각 메일함의 모든 메일이 들어오는데 어디에 있는 메일인지 알기 위해
=> feat(fe): 전체메일함 클릭시 각 메일이 어디 메일함에 들어있는지 보이도록 추가

infra/maildb/src/app.js, infra/maildb/src/format.js
1. format의 valueOfMailTemplate에 html 추가
1. html값도 DB에 저장하는 것으로 변경하였으므로
=> [Infra] parseMailContent 반환값에 html 추가

web/components/MailArea/MailTemplate/index.js
1. 오늘 쓰여진 메일이면 시간만 출력되도록 수정
1. nowMonth 지우지마셈
=> [FE/HOTFIX] 오늘 쓰여진 메일이면 시간만 출력되도록 수정

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/index.js
=> [FE] master merge

web/components/Aside/index.js, web/components/MailArea/index.js
불필요한 로직 제거 및 최적화
1. useEffect대신 useMemo사용 
1. 더 적절해보임
=> perf(fe/mail): useEffect대신 useMemo사용

web/components/Aside/dialog-data.js, web/components/Aside/index.js
1. 메일함 추가/수정/삭제 버그 fix
1. 입력 값에 trim을 적용하여 앞뒤로 공백을 제거해주어 에러 방지
2. 추가/수정/삭제 버튼 클릭시 비활성화하여 에러 발생 방지
=> [FE] 메일함 추가/수정/삭제 버그 fix

server/src/libraries/save-to-infra.js, server/src/v1/mail/box/service.js
1. imap 에러처리 추가
1. 그냥 throw시 서버가 죽기 때문
=> fix(be): imap 에러처리 추가

README.md, server/src/libraries/save-to-infra.js, server/src/v1/mail/box/service.js, server/src/v1/mail/service.js, server/test/libraries/mail/attachment.spec.js, server/test/mail/api.spec.js, server/test/mail/service.spec.js, web/components/Aside/dialog-data.js, web/components/Aside/index.js, web/components/MailArea/MailTemplate/index.js, web/components/MailArea/index.js
메일리스트 시간정렬 버그 수정
메일박스 IMAP 에러처리
메일박스 요청버튼 비활성화
=> release 0.1.2 

web/components/MailArea/index.js
1. categoryNoByName을 매개변수로 전달하지 않았기 때문에 발생하여 추가
1. 실수로 빠뜨림..
=> fix(fe/mail-area): 삭제 시 발생하는 unexpected error 수정

web/components/ReadMail/FileList/index.js, web/config/index.js, web/utils/request.js
1. server api 분리
1. 곳곳에 퍼져있는 주소를 한곳에서 관리
=> fix(fe/config): server api 분리

web/components/Forms/RegisterForm/index.js, web/components/GlobalStyle/index.js, web/components/LogoutButton/index.js, web/components/Profile/index.js, web/components/Profile/styled.js, web/pages/help/id.js, web/pages/help/password.js, web/pages/profile.js, web/pages/register.js, web/utils/error-message.js, web/utils/error-parser.js, web/utils/history.js, web/utils/storage.js
1. 로그아웃시 상태를 초기화 하도록 함
2. 로그아웃 버튼 모서리를 클릭시 홈페이지로 이동하는 문제 해결
3. 아이디찾기, 비밀번호찾기, 회원가입 페이지 뒤로가기 버튼 추가
1. 로그아웃시 상태를 초기화 하도록 하여 상태와 관련된 버그를 방지
2. 사용자 편의성을 위해 각 페이지에 뒤로가기 버튼 추가
=> [FE] 로그아웃시 상태 초기화 및 아이디 찾기, 비밀번호 찾기, 회원가입 페이지 뒤로가기 버튼 추가

server/src/app.js, server/src/middlewares/passport.js, server/src/v1/users/controller.js
1. 비밀번호 변경후 req.user의 password 변경
1. 클라이언트에서 비밀번호 변경 후 메일 전송시 발생하는 에러 해결
=> fix(be): 비밀번호 변경 후 req.user의 password 변경

server/src/libraries/mimemessage.js, server/src/v1/mail/service.js
1. mime message date 수정
1. moment를 다른 곳에서도 사용하고 있고 사용하기 간편함
=> [BE] mime message date 수정

infra/maildb/src/app.js, infra/maildb/src/env.js, infra/maildb/src/ncloud.js, infra/maildb/src/package-lock.json, infra/maildb/src/package.json, infra/postfix/advanced-content-filter.py
1. 인프라에서 보낸메일 저장
2. 메일의 크기가 클 수 있으므로 파일로 저장하고 파일의 path를 인자로 보내줌
1. 타 MUA에서 메일을 전송할 때에도 데이터베이스에 저장하기 위해
2. 메일의 크기가 크면 쉘 스크립트에서는 변수에 담을 수 없기 때문에 파일로 저장하여 path를 전달하도록 함
- postfix는 큐를 사용하여 메일을 보내므로 메일의 훼손 염려가 없음
=> [Infra] 작업 동기화

web/components/Header/Search/Input/InputDate.js, web/components/Header/Search/Input/date.css, web/components/Header/Search/Input/index.js, web/components/Header/Search/Input/styled.js, web/components/Header/Search/index.js, web/components/Header/Search/styled.js, web/components/Header/index.js, web/components/Header/styled.js, web/components/MailArea/Paging/PageNumber/index.js, web/components/MailArea/Paging/PageNumber/styled.js, web/components/MailArea/Tools/index.js, web/components/MailArea/Tools/styled.js, web/components/MailArea/index.js, web/components/MailArea/styled.js, web/components/WriteMail/styled.js, web/package-lock.json, web/package.json
1. 메일페이지 CSS 변경
1. 보이는게 전부다. 예뻐야함
=> fix(fe/css): FE 메일페이지 css 수정 #373

web/components/MailArea/Tools/index.js, web/components/ReadMail/Tools/index.js
1. 휴지통과 다른 메일함 버튼이 다르도록 해야함
1. category_no를 확인하여 visible 처리
원래 됐는데 재호 요구사항에 충족하다가 실수함 ㅎ
=> fix(fe/compontents/tools): swapButtonSetView() 수정

web/components/Aside/index.js, web/components/MailArea/Paging/index.js, web/components/MailArea/styled.js
1. nextButton 로직수정
1. endPage 와 totalPage가 같다면, nextButton이 없어야함
=> fix(fe/paging): nextButton 로직수정

server/src/libraries/exception/error-code.js, server/src/libraries/mail-util.js, server/src/libraries/save-to-infra.js
1. imap 서버와 연결하여 메일 이동시키기
1. node imap에서 여러 메일을 search하기 위해서는 OR 연산자를 사용하여야 하는데, 최대 2개의 인자를 가지기 때문에 아래와 같이 OR를 중첩하여 사용하여야 했음. 따라서 `message id`를 배열로 받아서 아래의 형식으로 바꾸어주는 함수를 만들게 되었음
```javascript
[ 'OR',
'foo',
[ 'OR',
'bar',
[ 'OR',
'baz',
'quux' ]
]
]
```
=> [BE] imap 서버와 연결하여 메일 이동시키기

web/.eslintrc.json, web/components/Header/Search/Input/InputDate.js, web/components/Header/Search/Input/index.js, web/components/Header/Search/context/index.js, web/components/Header/Search/index.js, web/components/MailArea/index.js, web/pages/index.js, web/utils/url/change-query.js
1. search UI에 이벤트 연동
1. search도 부피가 큰 컴포넌트임.
2. 구글을 모방함
1. 카테고리나 페이지 이동시 search를 제거할 것인가에 대한 고민을 했지만, 제거하지 않기로 생각하고 구현함.
2. 검색내용을 reset해줄수 있는 button을 만들것인가에 대한 고민은, 일단 검색부터 만들고 생각
=> feat(fe/search): search UI에 이벤트 연동

web/components/Header/Search/Input/InputDate.js, web/components/Header/Search/Input/index.js, web/components/Header/Search/context/index.js, web/components/Header/Search/index.js
=> fix(fe/search): 상세검색 데이터 포맷변경

server/src/bin/www.js, server/src/libraries/validation/mail.js, server/src/v1/mail/index.js, server/src/v1/mail/search/controller.js, server/src/v1/mail/search/index.js, server/src/v1/mail/search/service.js, server/src/v1/mail/service.js, server/test/libraries/mail/searchQuery.spec.js
1. 상세검색 기능
1. 기존코드를 최대한 활용함.
2. 기존 mail list소스에서 query의 파라미터만 변했기때문에, 이에 대응하는 함수만 변경
=> feat(be/search): 상세검색

web/components/Header/Search/index.js, web/components/IndexLayout/index.js, web/components/MailArea/index.js, web/utils/url/change-query.js
1. general 서치 제공
1. advanced와 general의 search은 다름
2. 지메일을 참조함
=> feat(fe/search): general 서치 제공 #405

web/components/Header/Search/Input/InputDate.js, web/components/Header/Search/Input/index.js, web/components/Header/Search/context/index.js, web/components/Header/Search/index.js, web/components/Header/Search/styled.js, web/components/MailArea/Paging/index.js, web/utils/url/change-query.js
1. 상세검색 Reset버튼추가
2. 페이징시 기존쿼리 유지
1. 사용자 편의를 위해 Reset기능을 제공한다. 이렇게 하기위해서는 onChange를 이용해야함 흑흑
2. 기존쿼리를 유지하지 않으면 검색기능이 의미없어짐..
=> 상세검색 Reset버튼추가 및 페이징시 기존쿼리 유지 #413

server/src/libraries/exception/error-code.js, server/src/v1/users/service.js, server/test/user/service.spec.js
1. 회원가입시 아이디 중복 혹은 이메일 중복시 fieldError와 함께 반환
1. fieldError와 함께 넘겨주어 회원가입시 어떤 부분에서 에러가 났는지 확인 할 수 있도록 함
=> [BE] 회원가입시 아이디 중복 혹은 이메일 중복시 fieldError와 함께 반환

web/components/Forms/RegisterForm/index.js, web/utils/error-message.js, web/utils/error-parser.js
1. 회원가입시 서버에서 409에러 반환시 fieldErrors 파싱
1. fieldErrors에 따라 에러 메시지를 표시하도록 파싱 (이전에는 메시지 내용에 따라 에러 메시지 위치 결정)
=> [FE] 회원가입시 서버에서 409에러 반환시 fieldErrors 파싱

server/src/middlewares/sync-with-imap.js, server/src/v1/auth/index.js, server/src/v1/users/service.js
1. syncWithImap 함수는 api 테스트시 제거
1. 테스트시 imap은 test db와 연결이 되어 있지 않아 발생하는 에러 해결
=> [BE] syncWithImap 함수는 api 테스트시 미들웨어에서 제외

server/src/database/models/mail.js, server/src/database/models/user.js, server/src/libraries/validation/mail.js, server/src/v1/mail/controller.js, server/src/v1/mail/index.js, server/src/v1/mail/search/controller.js, server/src/v1/mail/search/index.js, server/src/v1/mail/search/service.js, server/src/v1/mail/service.js, server/src/v1/users/service.js, server/test/libraries/mail/searchQuery.spec.js
1. 상세검색 tc추가
2. 휴지통 번호 세션관리
1. 검증이 필요했음.
2. 매번 db요청하는게 불필요해보임
=> 상세검색 tc추가 및 휴지통 번호를 세션에서 관리

web/components/Aside/index.js, web/components/MailArea/Tools/index.js, web/components/MailArea/Tools/styled.js, web/utils/url/change-query.js
1. 페이지당 메일갯수 기능추가
1. 형진쨔응이 만들어달라고함
=> feat(fe/tools): 페이지당 메일갯수 기능추가

server/src/libraries/mail-util.js, server/src/v1/admin/mail/service.js, server/src/v1/mail/service.js
1. 메일 전송시 기존에 만든 transporter 사용
1. 새로운 transporter를 만들지 않고 기존 만들어진 transporter를 사용하도록 하여 코드 개선
=> [BE] 메일 전송시 기존에 만든 transporter 사용

server/src/libraries/validation/mail.js, server/test/libraries/mail/quey.spec.js
1. perpagenum 검증 추가
1. 기존 로직을 활용
2. 최대한 적은 로직으로 기능완성 우왕굿
=> feat(be/mail): perpagenum 검증 추가

web/components/WriteMail/InputReceiver/index.js, web/components/WriteMail/Tools/index.js, web/package-lock.json
1. 여러 메일 복붙시 파싱
2. 메일 전송 버튼 버그
1. split을 활용하여서 regex를 활용하지 않도록 하였음
2. 비활성화하는 것이 좋은 방법이라 생각하였음
=> [FE] 여러 메일 복붙시 파싱/메일 전송 버튼 버그

web/components/Header/Search/index.js
1. #433 픽스
1. date는 Date type임
=> fix(fe/search): 검색 date필터시 에러  #433

web/components/MailArea/MailTemplate/index.js, web/components/MailArea/index.js
1. mailarea categories 제거
1. 불필요한 연산만함
2. categoryNameByNo state를 이용하면 됨
=> refactor(fe/mail): 불필요한 categories제거

web/components/Aside/dialog-data.js, web/components/Aside/index.js
1. 변수명 수정
1. custom으로 명명하여 리뷰어를 헷갈리게함
ㅈㅅ ㅎㅎ..
=> [FE] 변수명 수정

server/src/database/models/mail.js, server/src/libraries/mail-util.js, server/src/middlewares/sync-with-imap.js, server/src/v1/admin/mail/service.js
1. 유저별로 예약 메일을 전송하도록 함
2. findAllMessasgeIds에서 예약 메일은 쿼리문에서 제외
1. 데이터베이스에서 유저를 한 번만 불러오도록 하였으며 유저별 메일을 하나씩 처리하여 "[timed out while authenticating with server](https://github.com/mscdex/node-imap/issues/763)" 에러 해결
2. findAllMessasgeIds에서 예약 메일은 쿼리문에서 제외시켜 로그인시 예약 메일이 삭제되는 일 방지
=> [BE] 유저별 예약 메일 전송, findAllMessasgeIds 쿼리에서 예약 메일은 제외하도록 함

web/components/Aside/dialog-data.js, web/components/Aside/index.js
1. get dialog부분 bug hotfix
1. type은 반드시 주어야 함
=> [FE/Hotfix] get dialog부분 bug hotfix

web/components/Aside/dialog-data.js, web/components/Aside/index.js
1. dialog parameter 객체화
1. anti pattern T^T
=> [FE] dialog parameter 객체화

server/src/v1/mail/service.js
=> fix(be/mail): 파일전송시 첨부파일여부 저장

web/components/ReadMail/index.js
1. 첨부파일 없을때만 요청한다.
2. 읽은 파일은 update 요청하지 않는다.
1.
=> fix(fe/readmail): 첨부파일 여부에 따라 request

server/src/database/models/mail-template.js, server/src/database/models/mail.js, server/src/middlewares/sync-with-imap.js
1. 메일 컬럼 has_attachment를 메일 템플릿으로 이동
1. 첨부파일여부를 메일에 저장할 경우 중복임
=> fix(be/mail): 메일모델 수정

web/components/ReadMail/index.js
=> fix(fe/readmail): db컬럼 변화에 따른 변경

web/components/Forms/LoginForm/index.js, web/pages/login.js
1. 로그인 페이지에서 페이지 이동 시 발생하는 이벤트 등록
1. 로그인 폼은 페이지 이동 시 발생하는 이벤트 등록을 제거하여 폼의 역할만 하도록 함
=> fix(fe): 로그인 페이지에서 페이지 이동 시 발생하는 이벤트 등록

infra/maildb/src/format.js
1. 메일 저장할 때 mail 테이블에 has attachment 추가 저장
1. 메일이 attachment를 가지는지 먼저 확인이 가능하다면 db요청을 하지 않아도 되는 경우엔 안해도 되기 때문
=> [Infra] 메일 저장할 때 mail 테이블에 has attachment 추가 저장

server/src/v1/mail/service.js
1. 메일 저장시 has attachments를 has attachment로 수정
1. 복수형으로 적었었음
=> [BE] 메일 저장시 has attachments를 has attachment로 수정

web/components/Aside/dialog-data.js, web/components/WriteMail/Tools/index.js
1. refactor(리뷰지적부분)
1. 리뷰어분께 지적을 받았습니당
=> [FE] refactor(리뷰지적부분)

web/components/LogoutButton/index.js, web/package-lock.json, web/package.json, web/utils/storage.js
1. next@canary 모듈 설치
2. 함수명 변경 (clear => clearStorage)
1. 해당 모듈을 설치하여 새로고침 혹은 주소창 url 입력 후 뒤로가기 버튼 클릭시 라우팅이 되지 않는 문제 해결할 수 있음
[Go back browser button does not refresh page](https://github.com/zeit/next.js/issues/9449)
2. 함수명을 명확히 변경
#325
=> [FE] next@canary 모듈 설치, 함수명 변경

server/src/libraries/imap.js, server/src/v1/mail/service.js
1. 내게쓰기 꺾쇄 들어가던 부분 수정
2. 받은 메일함으로 이동시에도 메일함 이름 수정
1. 형진짜응의 버그발견
=> [BE] 내게쓰기 꺾쇄 들어가던 부분 수정 / 받은 메일함으로 이동시에도 메일함 이름 수정

web/utils/request.js
1. axios timeout 제거
1. 로그인시 타임아웃이 되는 현상 방지
=> [FE] axios timeout 제거

web/components/MailArea/Tools/index.js, web/components/ReadMail/Tools/index.js, web/components/ReadMail/index.js
1. fetchedMail.has_attachment -> MailTemplate.has_attachment로 수정
1.
=> [FE] 첨부파일 읽기 에러 수정

web/components/IndexLayout/index.js, web/components/MailArea/Tools/index.js, web/components/MailArea/Tools/styled.js, web/pages/index.js
=> fix(fe/tools): perPageNum 중앙정렬

web/components/ReadMail/index.js
=> fix(fe/read-mail): 첨부파일이 없는 경우 attachment 클리어

server/src/v1/admin/mail/service.js, server/src/v1/mail/controller.js
1. 예약 메일 전송시 html 정보도 함께 추가하여 전송
2. 예약 메일 전송 후 기존 예약 메일 삭제
3. 메일 작성시 예약 날짜 정보를 함께 줄 경우 예약 메일로 등록
1. 인프라에서 데이터베이스에 보낸 메일을 등록하기 때문에 기존 예약 메일은 삭제가 필요
2. 자기 자신에게 예약 메일을 보낼 수 있도록 함
=> [BE] 예약 메일 전송 관련 문제 해결

infra/maildb/src/app.js
=> fix(infra/maildb): html,text 모두 없는 경우 ''출력하도록 변경

web/components/WriteMail/Tools/index.js
1. 예약 메일을 보낼 경우 스낵바 메시지 변경
1. 메일 전송 성공 메시지보다 예약 성공 메시지를 보여주는게 맞을 것 같음
=> [FE] 예약 메일을 보낼 경우 스낵바 메시지 변경

web/components/ReadMail/index.js, web/components/WriteMail/Tools/index.js
=> [FE] merge to master
